# Change these first
owner: LGMOA-Oranziniai # Your GitHub organization or username, where this repository lives
repo: Puslapiu-stebejimas # The name of this repository

sites:
  - name: Olimpiados.lt
    url: https://olimpiados.lt
    assignees:
      - Oranziniai
      - Zviedrys
  - name: LitMO puslapis
    url: https://litmo.olimpiados.lt
    assignees:
      - Oranziniai
      - Zviedrys

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.olimpiados.lt
  # baseUrl: /Olimpiados.lt-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  # status-page
  activeIncidents: "Aktyvūs incidentai"
  allSystemsOperational: "Visos sistemos veikia"
  incidentReport: "Incidento #$NUMBER ataskaita →"
  activeIncidentSummary: "Atidaryta $DATE su $POSTS pranešimais"
  incidentTitle: "Incidento $NUMBER detalės"
  incidentDetails: "Incidento detalės"
  incidentFixed: "Išspręsta"
  incidentOngoing: "Vyksta"
  incidentOpenedAt: "Atidaryta"
  incidentClosedAt: "Uždaryta"
  incidentViewOnGitHub: "Peržiūrėti ir užsiprenumeruoti GitHub"
  incidentCommentSummary: "Paskelbta $DATE, autorius $AUTHOR"
  incidentBack: "← Atgal į visus incidentus"
  pastIncidents: "Ankstesni incidentai"
  pastIncidentsResolved: "Išspręsta per $MINUTES minutes su $POSTS pranešimais"
  liveStatus: "Gyva būsena"
  overallUptime: "Bendras veikimo laikas: $UPTIME"
  overallUptimeTitle: "Bendras veikimo laikas"
  averageResponseTime: "Vidutinis atsako laikas: $TIMEms"
  averageResponseTimeTitle: "Vidutinis atsakas"
  sevelDayResponseTime: "7 dienų atsako laikas"
  responseTimeMs: "Atsako laikas (ms)"
  up: "Veikia"
  down: "Neveikia"
  degraded: "Sumažėjęs našumas"
  ms: "ms"
  loading: "Kraunasi"
  navGitHub: "GitHub"
  footer: "Šis puslapis yra [atviro kodo]($REPO), valdomas [Upptime](https://upptime.js.org)"
  rateLimitExceededTitle: "Viršytas užklausų limitas"
  rateLimitExceededIntro: "Viršijote leidžiamų užklausų per valandą skaičių, todėl turėsite palaukti, kol vėl galėsite pasiekti šią svetainę. Arba galite pridėti GitHub asmeninį prieigos raktą, kad galėtumėte toliau naudotis svetaine."
  rateLimitExceededWhatDoesErrorMean: "Ką reiškia ši klaida?"
  rateLimitExceededErrorMeaning: "Ši svetainė naudoja GitHub API, kad gautų realaus laiko duomenis apie mūsų svetainių būklę. Pagal numatytuosius nustatymus, GitHub leidžia kiekvienam IP adresui atlikti 60 užklausų per valandą, kurias jūs jau sunaudojote."
  rateLimitExceededErrorHowCanFix: "Kaip tai ištaisyti?"
  rateLimitExceededErrorFix: "Galite palaukti valandą, kol jūsų IP adreso limitas bus atstatytas. Arba galite pridėti savo GitHub asmeninį prieigos raktą, kuris suteikia papildomus 5 000 užklausų per valandą."
  rateLimitExceededGeneratePAT: "Sužinokite, kaip sugeneruoti asmeninį prieigos raktą"
  rateLimitExceededHasSet: "Jūs turite nustatytą asmeninį prieigos raktą."
  rateLimitExceededRemoveToken: "Pašalinti raktą"
  rateLimitExceededGitHubPAT: "GitHub asmeninis prieigos raktas"
  rateLimitExceededCopyPastePAT: "Nukopijuokite ir įklijuokite savo raktą"
  rateLimitExceededSaveToken: "Išsaugoti raktą"
  errorTitle: "Įvyko klaida"
  errorIntro: "Bandant gauti naujausią būsenos informaciją įvyko klaida."
  errorText: "Galite pabandyti dar kartą po kelių akimirkų."
  errorHome: "Eiti į pagrindinį puslapį"
  pastScheduledMaintenance: "Ankstesnė planuota priežiūra"
  scheduledMaintenance: "Planuota priežiūra"
  scheduledMaintenanceSummaryStarted: "Pradėta $DATE trukmė $DURATION minučių"
  scheduledMaintenanceSummaryStarts: "Prasidės $DATE trukmė $DURATION minučių"
  startedAt: "Prasidėjo"
  startsAt: "Prasidės"
  duration: "Trukmė"
  durationMin: "$DURATION minučių"
  incidentCompleted: "Užbaigta"
  incidentScheduled: "Planuojama"
  duration24H: "24 val."
  duration7D: "7 d."
  duration30D: "30 d."
  duration1Y: "1 m."
  durationAll: "visa"
  locale: "lt-LT"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
